spring.application.name=SocialDev

spring.datasource.url=jdbc:postgresql://localhost:5432/socialdev
spring.datasource.username=nyanminhtet
spring.datasource.password=r00t1t

spring.jpa.hibernate.ddl-auto=update
